name: Docker Build and Push Image to DockerHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image and Push to DockerHub
        uses: docker/build-push-action@v6.3.0
        with:
          file: dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thuinfo-web:latest
          push: true
